# Generated by Django 4.2 on 2023-09-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="text",
            field=models.TextField(),
        ),
    ]
