# Generated by Django 4.2 on 2023-08-27 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="сategory",
            new_name="category",
        ),
    ]
